openapi: 3.0.3
info:
  title: RemediateEmail
  description: This is the core API call which connects to different agent
  version: 1.0.0
servers:
  - url: https://ai-dev.beakops.com/api/bitc
paths:
  /runs/copilot/stream:
    post:
      summary: This is the core API call which connects to different agent
      operationId: RemediateEmail
      security:
        - ApiKeyAuth: []
      parameters:
        - name: opengpts-user-id
          in: header
          required: true
          schema:
            type: string
          description: The BeakOps user ID.
        - name: emailid
          in: header
          required: true
          schema:
            type: string
            format: email
          description: The email ID of the user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - content
                - assistant_id
              properties:
                content:
                  type: string
                  description: The message sent to the copilot.
                  example: Hi
                assistant_id:
                  type: string
                  description: Unique identifier of the copilot assistant.
                  example: cfb458bb-09d1-4131-8b03-2b6249750eed
      responses:
        '200':
          description: Streamed response from the copilot.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: The response message from the copilot.
        '400':
          description: Bad request (e.g. invalid assistant_id).
        '401':
          description: Unauthorized (invalid API key).
        '500':
          description: Internal server error.
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: API-Key
