openapi: 3.0.0
info:
  title: BeakGuard Email Remediation API
  description: Email remediation API compatible with Security Copilot VS Code Extension
  version: "1.0.0"
servers:
  - url: https://graph.microsoft.com/beta/security/collaboration/analyzedEmails
    description: Microsoft Graph Security API
paths:
  /remediate:
    post:
      operationId: remediateEmail
      summary: Remediate a single email
      description: Move a single email to junk folder
      security:
        - oauth2: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - networkMessageId
                - recipientEmailAddress
              properties:
                networkMessageId:
                  type: string
                  description: Network message ID from EmailEvents
                  example: "73ca4154-58d8-43d0-a890-08dc18c52e6d"
                recipientEmailAddress:
                  type: string
                  format: email
                  description: Email address of the recipient
                  example: "user@contoso.com"
      responses:
        '202':
          description: Accepted - remediation initiated
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://login.microsoftonline.com/ea51d8d3-3565-4bd4-9ab0-77c9c5e5693d/oauth2/v2.0/token
          scopes:
            https://graph.microsoft.com/.default: Default scope
