openapi: 3.0.0
info:
  title: Microsoft Graph Security Email Remediation API
  description: API for remediating analyzed emails using Microsoft Graph Security Beta API
  version: "1.0.0"
servers:
  - url: https://graph.microsoft.com/beta
    description: Microsoft Graph Beta API
paths:
  /security/collaboration/analyzedEmails/remediate:
    post:
      operationId: RemediateAnalyzedEmail
      summary: Remediate analyzed emails by moving to junk folder
      description: Remove potential threats from end users mailboxes
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - displayName
                - description
                - severity
                - action
                - remediateSendersCopy
                - networkMessageId
                - recipientEmailAddress
              properties:
                displayName:
                  type: string
                  description: Name of remediation action
                  example: "BeakGuard Email Remediation"
                description:
                  type: string
                  description: Description of remediation
                  example: "Moving suspicious email to junk folder"
                severity:
                  type: string
                  enum: ["low", "medium", "high"]
                  description: Severity level of the remediation
                  example: "medium"
                action:
                  type: string
                  enum: ["moveToJunk", "moveToInbox", "softDelete", "hardDelete", "moveToDeletedItems"]
                  description: Action to perform on the email
                  example: "moveToJunk"
                remediateSendersCopy:
                  type: boolean
                  description: Whether to remediate sender's copy
                  example: false
                networkMessageId:
                  type: string
                  description: Network message ID from EmailEvents
                  example: "73ca4154-58d8-43d0-a890-08dc18c52e6d"
                recipientEmailAddress:
                  type: string
                  format: email
                  description: Email address of the recipient
                  example: "user@contoso.com"
            example:
              displayName: "BeakGuard Spoofing Remediation"
              description: "Moving spoofed email to junk folder"
              severity: "medium"
              action: "moveToJunk"
              remediateSendersCopy: false
              networkMessageId: "73ca4154-58d8-43d0-a890-08dc18c52e6d"
              recipientEmailAddress: "user@contoso.com"
      responses:
        '202':
          description: Accepted - remediation initiated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Remediation task ID
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Azure AD Bearer token with SecurityAnalyzedMessage.ReadWrite.All permission
