openapi: 3.0.0
info:
  title: Microsoft Graph Security Email Remediation API
  description: Move suspicious emails to junk folder using Microsoft Graph Security
  version: "v1"
servers:
  - url: https://graph.microsoft.com/beta
paths:
  /security/collaboration/analyzedEmails/remediate:
    post:
      operationId: RemediateEmail
      summary: Move email to junk folder
      description: Remediate suspicious email by moving to junk folder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - networkMessageId
                - recipientEmailAddress
              properties:
                displayName:
                  type: string
                  default: "BeakGuard Email Remediation"
                  description: Name of remediation action
                description:
                  type: string
                  default: "Moving suspicious email to junk folder"
                  description: Description of remediation
                severity:
                  type: string
                  enum: ["low", "medium", "high"]
                  default: "medium"
                  description: Severity level
                action:
                  type: string
                  enum: ["moveToJunk"]
                  default: "moveToJunk"
                  description: Action to perform - fixed to moveToJunk
                remediateSendersCopy:
                  type: boolean
                  default: false
                  description: Whether to remediate sender's copy
                analyzedEmails:
                  type: array
                  description: Array of emails to remediate
                  minItems: 1
                  items:
                    type: object
                    required:
                      - networkMessageId
                      - recipientEmailAddress
                    properties:
                      networkMessageId:
                        type: string
                        description: Network message ID from EmailEvents
                      recipientEmailAddress:
                        type: string
                        format: email
                        description: Email address of the recipient
                # Input parameters for transformation
                networkMessageId:
                  type: string
                  description: Network message ID from EmailEvents
                recipientEmailAddress:
                  type: string
                  format: email
                  description: Email address of the recipient
      responses:
        "202":
          description: Accepted - email remediation initiated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Email successfully queued for remediation"
                  remediationId:
                    type: string
                    example: "rem_12345-abcd-6789-efgh"
        "400":
          description: Bad Request - Invalid parameters
        "401":
          description: Unauthorized - Invalid authentication
        "403":
          description: Forbidden - Insufficient permissions
        "500":
          description: Internal Server Error
